Bluntsord/realtime notes updated
AY2122S1-CS2103T-W16-1/tp pull request #307
Opened 2021-11-03 05:57 UTC by Bluntsord

Make notes have realtime update

Fixes #218 

Previously we did not save everytime we wrote the notes. We were lucky that it was caught when running commands in logicManager. Hence, it saving only when we ran a new command.

![image](https://user-images.githubusercontent.com/64136922/140015402-3570becd-9b02-4cef-bc78-e3200b3c3d23.png)

2021-11-03 06:21 UTC, bharathcs commented
Niceeeee. This makes sense. But tbh we shouldn't swallow an error from `saveAddressBook`. 

If the file gets corrupted / we have some IO problem, it should throw an exception and shut down the app. 

This can either be just an uncaught runtime exception, or even better, call on the method fatalerror and shutdown which is either in `UiManager` or `MainWindow`.

2021-11-03 06:22 UTC, bharathcs requested changes
Niceeeee. This makes sense. But tbh we shouldn't swallow an error from `saveAddressBook`. 

If the file gets corrupted / we have some IO problem, it should throw an exception and shut down the app. 

This can either be just an uncaught runtime exception, or even better, call on the method fatalerror and shutdown which is either in `UiManager` or `MainWindow`.

2021-11-03 06:22 UTC, Bluntsord commented
> Niceeeee. This makes sense. But tbh we shouldn't swallow an error from `saveAddressBook`.
> 
> If the file gets corrupted / we have some IO problem, it should throw an exception and shut down the app.
> 
> This can either be just an uncaught runtime exception, or even better, call on the method fatalerror and shutdown which is either in `UiManager` or `MainWindow`.

So I should make the function throw an error? Can cfm?

2021-11-03 06:28 UTC, bharathcs commented
> So I should make the function throw an error? Can cfm?

You can have the PersonAdapter's edit throw a runtime exception (unchecked). This would cause the app to shut down and the command prompt terminal to show an exception error.

Or you can replace printstacktrace that you wrote here with `((UiManager) ui).showFatalErrorDialogAndShutdown()` 

The first way is the best way but idrc, the first way is easier to write and doesn't require any changes. We can do the first way to save time now since we're so close to the end.

2021-11-04 06:36 UTC, bharathcs approved these changes

2021-11-04 06:36 UTC, bharathcs commented on src/main/java/donnafin/model/ModelManager.java
> +        //Need to run save addressBook if not it wont save.
```suggestion
        // Required to save changes from the model representation 
        // in Java memory to the user's local storage.
```

2021-11-04 06:37 UTC, bharathcs approved these changes
Nice work!!

2021-11-05 01:50 UTC, bharathcs approved these changes
Nice work, feel free to commit if you like but I have a suggestion to reduce code duplication if you like.

2021-11-05 01:50 UTC, bharathcs commented on src/main/java/donnafin/logic/PersonAdapter.java
> +        }
```suggestion
        trySavingAddressBook();
```

:warning: Do not commit this directly, this is not complete.

What if we replace all these duplicated code fragments with a call to a method that does exactly this. A private method `trySavingAddressBook()` in `PersonAdapter` would work right?

2021-11-05 04:12 UTC, bharathcs approved these changes
LGTM!

2021-11-05 04:12 UTC, merged